export const drugs = {
    Longevity: [
      {
        name: "NAD+ Injection",
        summary: "Nicotinamide adenine dinucleotide (NAD+) helps improve cellular metabolism, energy production, and overall cellular health.",
        description: "Nicotinamide adenine dinucleotide (NAD+) is a vital coenzyme found in every cell of your body. It plays a crucial role in cellular metabolism, energy production, and overall cellular health. By enhancing NAD+ levels, you can support numerous physiological functions that contribute to optimal health and longevity.",
        benefits: ["Anti Aging", "Cellular Repair", "Energy Boost"],
        pricePerMonth: "$199",
        fullPrice: "$599",
        image: "NAD.PNG",
      },
      {
        name: "Glutathione Injection",
        summary: "A powerful antioxidant that detoxifies, reduce oxidative stress, and enhance immune function.",
        description: "Glutathione injections are a powerful antioxidant treatment that support detoxification, reduce oxidative stress, and enhance immune function. By protecting cells from free radical damage, promoting healthy aging, and boosting skin clarity and radiance, glutathione helps you feel more energized, refreshed, and glowing from within.",
        benefits: ["Reduced Inflammation", "Skin, Hair Health", "Cellular Repair"],
        pricePerMonth: "$179",
        fullPrice: "$529",
        image: "Glutathione.PNG",
      },
    ],
    "Weight Loss": [
      {
        name: "Semaglutide + B12",
        summary: "Supports weight loss by regulating appetite and boosting metabolism.",
        description: "A GLP-1 receptor agonist that curbs appetite, boosts metabolism, and supports energy. Vitamin B12 helps prevent fatigue, making weight loss easier and more sustainable.", 
        benefits: ["Appetite Control", "Metabolism Boost", "Energy Enhancement"],
        pricePerMonth: "$299",
        fullPrice: "$899",
        image: "SemaglutideB12.png",
      },
      {
        name: "Tirzepatide + B12",
        summary: "Enhances weight loss by controlling blood sugar and metabolism.",
        description: "A dual-action GLP-1 & GIP receptor agonist that reduces hunger, regulates blood sugar, and enhances fat loss. B12 supports energy and overall well-being.",
        benefits: ["Blood Sugar Control", "Weight Management", "Energy Boost"],
        pricePerMonth: "$329",
        fullPrice: "$999",
        image: "TirzepatideB12.png",
      },
      {
        name: "Semaglutide + B12 Microdose",
        summary: "A lower-dose alternative for gradual weight loss and appetite regulation.",
        description: "A lower-dose option for gradual, sustained weight loss and appetite regulation with added B12 for energy support.", 
        benefits: ["Gradual Appetite Control", "Metabolism Boost", "Sustained Energy"],
        pricePerMonth: "$199",
        fullPrice: "$699",
        image: "SemaglutideB12.png"
      },
      {
        name: "Tirzepatide + B12 Microdose",
        summary: "A microdose option for steady weight management and blood sugar balance.",
        description: "A microdose version for steady weight reduction and metabolic control with B12 for sustained energy levels.", 
        benefits: ["Blood Sugar Stability", "Slow & Steady Weight Loss", "Energy Support"],
        pricePerMonth: "$249",
        fullPrice: "$799",
        image: "TirzepatideB12.png"
      }
    ],
    "Sexual Health": [
      {
        name: "PT-141",
        summary: "Enhances sexual desire and treats dysfunction by acting on the brain’s arousal pathways, improving sexual health and satisfaction.",
        description: "PT-141 is a supplement used primarily for the treatment of sexual dysfunction and enhancement of sexual desire by acting directly on the brain’s pathways involved in sexual arousal, providing a unique and effective approach to improving sexual health and satisfaction.", 
        benefits: ["Enhanced Libido", "Improved Mood", "Increased Melanin"],
        pricePerMonth: "$219",
        fullPrice: "$438",
        image: "PT-141.PNG", // Make sure this URL is correct
      }
    ],
    "Single Peptide": [
    {
      name: "AOD-9604",
      summary: "A peptide that enhances fat metabolism and supports weight loss.",
      description: " AOD-9604 is a modified fragment of human growth hormone (HGH) designed to accelerate fat metabolism. It helps break down fat, increase energy levels, and support weight loss efforts without impacting blood sugar levels. ", 
      benefits: ["Fat Burning", "Metabolism Boost", "Weight Management"],
      pricePerMonth: "$250",
      fullPrice: "$750",
      image: "AOD-9604.jpeg",
    },
    {
      name: "BPC-157",
      summary: "Promotes healing of muscles, tendons, and gut lining.",
      description: " BPC-157 is a powerful peptide known for its regenerative properties. It aids in tissue healing, speeds up recovery from injuries, and supports gut health by reducing inflammation and promoting cellular repair. ",
      benefits: ["Injury Recovery", "Gut Health", "Tissue Repair"],
      pricePerMonth: "$189",
      fullPrice: "$569",
      image: "BPC-157.PNG",
    },
    {
      name: "DSIP",
      summary: "A peptide that improves sleep and reduces stress.",
      description: " Delta Sleep-Inducing Peptide (DSIP) promotes restful sleep, reduces stress, and supports the body's natural sleep-wake cycle. It helps in relaxation, making it beneficial for individuals with insomnia or high stress. ",
      benefits: ["Sleep Improvement", "Stress Reduction", "Relaxation"],
      pricePerMonth: "$210",
      fullPrice: "$620",
      image: "DSIP.PNG",
    },
    {
      name: "Epithalon",
      summary: "Known for its anti-aging properties and cell regeneration.",
      description: "Epithalon is a peptide that stimulates telomerase activity, which helps extend cell lifespan. It is widely used for its anti-aging effects, promoting longevity, cellular repair, and overall wellness.",
      benefits: ["Longevity", "Anti-Aging", "Cell Regeneration"],
      pricePerMonth: "$240",
      fullPrice: "$720",
      image: "Epithalon.PNG",
    },
    {
      name: "GHK-Cu",
      summary: "A copper peptide used for skin rejuvenation and hair growth.",
      description: "GHK-Cu is a naturally occurring copper peptide known for its regenerative properties. It promotes skin elasticity, reduces wrinkles, supports hair regrowth, and enhances wound healing.",
      benefits: ["Skin Rejuvenation", "Hair Growth", "Tissue Repair"],
      pricePerMonth: "$269",
      fullPrice: "$799",
      image: "GHK-Cu.PNG",
    },
    {
      name: "Gonadorelin",
      summary: "Used to stimulate natural hormone production.",
      description: "Gonadorelin stimulates the production of luteinizing hormone (LH) and follicle-stimulating hormone (FSH), promoting balanced hormone levels. It is commonly used for reproductive health and hormone optimization.",
      benefits: ["Hormone Stimulation", "Fertility Support", "Libido Boost"],
      pricePerMonth: "$190",
      fullPrice: "$570",
      image: "Gonadorelin.PNG",
    },
    {
      name: "IGF-LR3",
      summary: "A peptide known for promoting muscle growth and recovery.",
      description: "IGF-LR3 (Insulin-like Growth Factor-1 Long R3) is a powerful growth factor that enhances muscle repair, increases endurance, and accelerates muscle growth, making it popular among athletes and bodybuilders.",
      benefits: ["Muscle Growth", "Recovery Support", "Endurance Boost"],
      pricePerMonth: "$300",
      fullPrice: "$900",
      image: "IGF-LR3.PNG",
    },
    {
      name: "Kisspeptin",
      summary: "Supports reproductive hormone function and fertility.",
      description: "Kisspeptin is a peptide that plays a vital role in regulating reproductive hormones, promoting fertility, and supporting overall hormonal balance in both men and women.",
      benefits: ["Reproductive Health", "Hormone Balance", "Fertility Support"],
      pricePerMonth: "$215",
      fullPrice: "$645",
      image: "Kisspeptin.PNG",
    },
    {
      name: "LIPO-B",
      summary: "A lipotropic injection for fat metabolism and energy support.",
      description: "LIPO-B is a lipotropic injection that enhances fat metabolism, increases energy levels, and supports weight loss by breaking down fat more efficiently.",
      benefits: ["Fat Metabolism", "Energy Boost", "Weight Management"],
      pricePerMonth: "$230",
      fullPrice: "$690",
      image: "Lipo-B.jpeg",
    },
    {
      name: "LL-37",
      summary: "An antimicrobial peptide that supports immune function.",
      description: "LL-37 is a potent antimicrobial peptide that boosts the immune system, reduces inflammation, and aids in fighting infections.",
      benefits: ["Immune Support", "Anti-Microbial", "Inflammation Reduction"],
      pricePerMonth: "$260",
      fullPrice: "$780",
      image: "LL-37.jpeg",
    },
    {
      name: "Thymosin",
      summary: "Boosts immune system function and promotes healing.",
      description: "Thymosin is a peptide that enhances immune response, promotes tissue healing, and aids in recovery from illnesses or injuries.",
      benefits: ["Immune Boost", "Tissue Healing", "Recovery Support"],
      pricePerMonth: "$270",
      fullPrice: "$810",
      image: "Thymosin.jpeg",
    },
    {
      name: "MOTS-C",
      summary: "A mitochondrial peptide that enhances metabolism and longevity.",
      description: "MOTS-C is a unique mitochondrial-derived peptide that improves energy metabolism, supports longevity, and enhances physical performance.",
      benefits: ["Metabolic Boost", "Longevity", "Energy Production"],
      pricePerMonth: "$280",
      fullPrice: "$840",
      image: "MOTS-C.PNG",
    },
    {
      name: "Sermorelin",
      summary: "Stimulates the release of growth hormone naturally.",
      description: "Sermorelin is a peptide that stimulates the pituitary gland to release natural growth hormone, supporting muscle growth, fat loss, and overall vitality.",
      benefits: ["Growth Hormone Stimulation", "Energy Boost", "Anti-Aging"],
      pricePerMonth: "$215",
      fullPrice: "$645",
      image: "Sermorelin.PNG",
    },
    {
      name: "TB500",
      summary: "Promotes healing of muscles, tendons, and ligaments.",
      description: "TB500 is a synthetic version of a naturally occurring healing peptide that accelerates tissue repair, reduces inflammation, and enhances recovery from injuries.",
      benefits: ["Tissue Repair", "Injury Recovery", "Inflammation Reduction"],
      pricePerMonth: "$250",
      fullPrice: "$750",
      image: "TB500.PNG",
    },
    {
      name: "Tesamorelin",
      summary: "Stimulates natural growth hormone production for fat loss and metabolism boost.",
      description: "Tesamorelin is a growth hormone-releasing peptide that enhances metabolism, reduces visceral fat, and supports body composition improvements.",
      benefits: ["Fat Loss", "Metabolism Boost", "Growth Hormone Stimulation"],
      pricePerMonth: "$320",
      fullPrice: "$960",
      image: "Tesamorelin.PNG",
    }
  ],
  "Peptide Blends": [
    {
      name: "Fountain of Youth",
      summary: "Epithalon / GHK-Cu - A regenerative blend that promotes skin rejuvenation, anti-aging, and tissue repair.",
      description: "This unique blend of Epithalon and GHK-Cu supports cellular regeneration, promotes youthful skin, and slows down aging by enhancing collagen production and DNA repair." ,
      benefits: ["Anti-Aging", "Skin Rejuvenation", "Tissue Repair"],
      pricePerMonth: "$299",
      fullPrice: "$899",
      image: "Fountain of Youth.PNG",
    },
    {
      name: "Recovery Blend",
      summary: "BPC-157 / GHK-Cu / KPV / TB500 - A blend designed for deep cellular repair, inflammation reduction, and faster recovery.",
      description: "This recovery-focused peptide combination enhances tissue repair, reduces inflammation, and accelerates healing, making it ideal for injuries, post-surgical recovery, and muscle restoration." ,
      benefits: ["Cellular Repair", "Inflammation Reduction", "Faster Healing"],
      pricePerMonth: "$279",
      fullPrice: "$849",
      image: "Recovery Blend.PNG",
    },
    {
      name: "Performance Blend",
      summary: "CJC / Ipamorelin - Enhances muscle growth, boosts recovery, and increases energy levels.",
      description: "A powerful combination of CJC and Ipamorelin, designed to increase growth hormone levels, enhance muscle development, and speed up post-exercise recovery." ,
      benefits: ["Muscle Growth", "Recovery Support", "Energy Boost"],
      pricePerMonth: "$320",
      fullPrice: "$960",
      image: "Performance Blend.PNG",
    },
    {
      name: "Sleep Blend",
      summary: "DSIP / BPC / CJC - Promotes restful sleep, reduces stress, and supports nighttime recovery.",
      description: "A blend of DSIP, BPC, and CJC that aids in sleep regulation, stress relief, and cellular restoration during nighttime, promoting overall well-being and recovery." ,
      benefits: ["Restful Sleep", "Stress Reduction", "Nighttime Recovery"],
      pricePerMonth: "$250",
      fullPrice: "$750",
      image: "Sleep Blend.PNG",
    },
    {
      name: "Cognitive Blend",
      summary: "Semax / Selank - Supports mental clarity, memory, and cognitive function.",
      description: "A nootropic peptide blend that enhances cognitive function, improves memory retention, and provides neuroprotection. Ideal for individuals looking to boost mental clarity and focus." ,
      benefits: ["Memory Enhancement", "Cognitive Function", "Neuroprotection"],
      pricePerMonth: "$275",
      fullPrice: "$825",
      image: "Cognitive Blend.PNG",
    },
    {
      name: "Focus Blend",
      summary: "Pinealon / PE22-28 / Selank - Enhances focus, reduces brain fog, and boosts mental performance.",
      description: "This blend is designed to optimize brain function by improving neurotransmitter activity, reducing mental fatigue, and enhancing concentration for better mental performance." ,
      benefits: ["Focus Enhancement", "Mental Performance", "Brain Clarity"],
      pricePerMonth: "$290",
      fullPrice: "$870",
      image: "Focus Blend.PNG",
    },
    {
      name: "Fat Burner Blend",
      summary: "AOD-9604 / MOTs-C / Tesamorelin - Accelerates fat metabolism, increases energy, and promotes weight loss.",
      description: "A powerful combination of peptides that work synergistically to enhance fat metabolism, increase energy production, and support sustainable weight loss." ,
      benefits: ["Fat Metabolism", "Weight Loss", "Energy Production"],
      pricePerMonth: "$310",
      fullPrice: "$930",
      image: "Fat Burner Blend.PNG",
    },
    {
      name: "Build Blend",
      summary: "IGF-LR3 - A powerful peptide combination for lean muscle growth and strength enhancement.",
      description: "A peptide blend formulated to stimulate muscle growth, enhance recovery, and improve endurance, making it ideal for athletes and individuals focused on strength training." ,
      benefits: ["Muscle Growth", "Strength Enhancement", "Endurance Boost"],
      pricePerMonth: "$330",
      fullPrice: "$990",
      image: "Build Blend.PNG",
    }
  ]
  };
  